Hepterakt/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from payments import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.payments_view),
    url(r'^payments/', include('payments.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^board/', include('board.urls')),
]

board/urls.py
from django.conf.urls import url

from . import views

app_name = "board"

urlpatterns = [
    url(r"^$", views.board, name="board"),
    url(r"^task/(?P<task_id>[-\w]+)/$", views.edit_task, name="edit-task"),
]

payments/urls.py
from django.conf.urls import url

from . import views

app_name = "payments"

urlpatterns = [
    url(r'^$', views.payments_view, name='payments'),
    url(r'^admin/', views.go_admin, name="go-admin"),
    url(r'^tasks/', views.tasks_view, name='tasks'),
    url(r'^download/', views.download, name='download'),
    url(r'^documents/', views.docs_view, name='documents'),
    url(r"^(?P<curr_year>[-\w]+)/(?P<curr_month>[-\w]+)/$", views.payments_view, name="filter-payments"),
    url(r'^hours/', views.hours_view, name='hours'),
]

board/models.py
from django.conf import settings
from django.db import models


class Task(models.Model):
    STATUSES = [
        ("To Do", "todo"),
        ("Doing", "doing"),
        ("Done", "done"),
        ("Backlog", "backlog"),
    ]

    name = models.CharField(max_length=200)
    status = models.CharField(
        choices=STATUSES, blank=True, default="todo", max_length=64
    )
    done_ind = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    assigned = models.ForeignKey('accounts.UserProfile', on_delete=models.SET_NULL, null=True)
    category = models.CharField(max_length=100, default=None)
    tag = models.CharField(max_length=50, default=None)
    description = models.TextField()
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    deadline = models.DateField()

    def __str__(self):
        return self.name

board/forms.py
import datetime
from django import forms
from .models import Task
from django.utils.safestring import mark_safe


class TaskForm(forms.ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'style': 'width: 400px'}),)
    deadline = forms.DateField(widget=forms.SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ), required=True)
    category = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'style': 'width: 400px'}),)
    tag = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'style': 'width: 400px'}),)

    class Meta:
        model = Task
        fields = ['name', 'assigned', 'category', 'tag', 'description', 'deadline']

board/views.py
import os
from datetime import datetime, date, timedelta
from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .models import Task
from .forms import TaskForm


def board(request):
    tasks = Task.objects.all().order_by('-id')
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = TaskForm()
    # import pdb; pdb.set_trace()
    return render(request, "board/board.html", {'tasks': tasks,
                                                'form': form})


def edit_task(request, task_id):
    task = Task.objects.filter(pk=task_id)
    # import pdb; pdb.set_trace()

    return render(request, "board/edit_task.html", {'tasks': task})

board/templates/board/board.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block headcontent %}

    <center>
        <h4>Board</h4>
    </center>

{% endblock %}

{% block content %}

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->
            <p class="panel-subtitle"><u>Task board</u></p>
            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <table class="table table-striped">

            {% for task in tasks %}
              <tr>
                <td>
                    <a href="{% url 'board:edit-task' task.pk %}" class=""><p><b>{{ task.name }}</b></p></a>
                    <p>{{ task.description|truncatechars:50 }}</p>
                    <p>#{{ task.pk }} {{ task.created }} by {{ task.owner}}</p>
                </td>
                <td>
                    <p>@ {{ task.assigned }}</p>
                    <p>
                        {% if task.status == 'Done' %}
                            <span class="label label-success">Done</span>
                        {% elif task.status == 'To Do' %}
                            <span class="label label-danger">To do</span>
                        {% elif task.status == 'Doing' %}
                            <span class="label label-warning">Doing</span>
                        {% else %}
                            <span class="label label-default">backlog</span>
                        {% endif %}
                    </p>
                    <p><i class="lnr lnr-calendar-full"></i> {{ task.deadline }}</p>
              </tr>
            {% endfor %}
            </table>

            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle">Add new task.</p>

            <form class="site-from" action=" {% url 'board:board' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
            <input type="submit" value="create">
            </form>

            <!-- END MYBLOCK -->

        </div>
    </div>

{% endblock %}

board/templates/board/closed.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block headcontent %}

    <center>
        <h4>Closed tasks</h4>
    </center>

{% endblock %}

{% block content %}

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->
            {% for task in tasks %}

                <p><b>{{ task.name }}</b></p>
                <p>{{ task.description}}</p>
                <p>{{ task.pk }}</p>
                <p>{{ task.created }}</p>
                <p>{{ task.owner}}</p>
                <p>{{ task.assigned }}</p>
                <p>{{ task.status }}</p>
                <p>{{ task.deadline }}</p>

            {% endfor %}
            <!-- END MYBLOCK -->

        </div>
    </div>

    <form class="site-form" action="{% url 'payments:download' %}" method="post" id="Download">
    {% csrf_token %}
        <button>
            <a href="{% url 'board:board' %}" class=""> Go back</a>
        </button>
        <button type="submit" form="Download" name="Filter" value="{{ user_region }}">
            Forget
        </button>
        <button type="submit" form="Download" name="Filter" value="{{ user_region }}">
            Reopen
        </button>        
    </form>

{% endblock %}

board/templates/board/edit_task.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block headcontent %}

    <center>
        <h4>Edit task</h4>
    </center>

{% endblock %}

{% block content %}

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->
            {% for task in tasks %}

                <p><b>{{ task.name }}</b></p>
                <p>{{ task.description}}</p>
                <p>{{ task.pk }}</p>
                <p>{{ task.created }}</p>
                <p>{{ task.owner}}</p>
                <p>{{ task.assigned }}</p>
                <p>{{ task.status }}</p>
                <p>{{ task.deadline }}</p>

            {% endfor %}
            <!-- END MYBLOCK -->

        </div>
    </div>

    <form class="site-form" action="{% url 'payments:download' %}" method="post" id="Download">
    {% csrf_token %}
        <button>
            <a href="{% url 'board:board' %}" class=""> Go back</a>
        </button>
        <button type="submit" form="Download" name="Filter" value="{{ user_region }}">
            Delete
        </button>
        <button type="submit" form="Download" name="Filter" value="{{ user_region }}">
            Update
        </button>
    </form>

{% endblock %}