Hepterakt/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from payments import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.payments_view),
    url(r'^payments/', include('payments.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^board/', include('board.urls')),
]

board/urls.py
from django.conf.urls import url

from . import views

app_name = "board"

urlpatterns = [
    url(r"^$", views.board, name="board"),
    url(r"^task/(?P<task_id>[-\w]+)/$", views.edit_task, name="edit-task"),
]

payments/urls.py
from django.conf.urls import url

from . import views

app_name = "payments"

urlpatterns = [
    url(r'^$', views.payments_view, name='payments'),
    url(r'^admin/', views.go_admin, name="go-admin"),
    url(r'^tasks/', views.tasks_view, name='tasks'),
    url(r'^download/', views.download, name='download'),
    url(r'^documents/', views.docs_view, name='documents'),
    url(r"^(?P<curr_year>[-\w]+)/(?P<curr_month>[-\w]+)/$", views.payments_view, name="filter-payments"),
    url(r'^hours/', views.hours_view, name='hours'),
]

payments/models.py
import os

from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)
    percent = models.PositiveIntegerField()

    def __str__(self):
        return self.name + " [%s]" % self.percent


class Payment(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField(auto_now_add=True)
    description = models.TextField(null=True, blank=True)
    value = models.DecimalField(decimal_places=2, max_digits=8)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    invoice = models.FileField(null=True, blank=True, upload_to='invoices/%Y/%m')
    invoice_location = models.CharField(max_length=100, blank=True)
    paid = models.BooleanField()

    def __str__(self):
        return '[%s] %s - %s' % (str(self.date), self.name, self.filename())

    def filename(self):
        return os.path.basename(self.invoice.name)

    class Meta:
        ordering = ('date',)


class Task(models.Model):
    name = models.CharField(max_length=200)
    done = models.BooleanField(default=False)
    deadline = models.DateField()

    def __str__(self):
        return self.name


class Month(models.Model):
    date = models.DateField()
    work_hours = models.PositiveIntegerField()
    vacation_hours = models.PositiveIntegerField(default=0)
    overtime_hours = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.date.year) + "." + str(self.date.month) + "-" + str(self.work_hours)

payments/forms.py
import datetime
from django import forms
from .models import Payment, Task, Month


class PaymentForm(forms.ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Name', 'style': 'width: 400px'}), label=False)
    value = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Value'}), label=False)
    description = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Description', 'style': 'width: 800px'}),
                                  label=False)
    invoice = forms.FileField(label=False, required=False)

    class Meta:
        model = Payment
        fields = ['name', 'paid', 'value', 'category', 'invoice', 'description']


class TaskForm(forms.ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Task name', 'style': 'width: 400px'}), label=False)
    deadline = forms.DateField(widget=forms.SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ), required=True)

    class Meta:
        model = Task
        fields = ['name', 'deadline']


class MonthForm(forms.ModelForm):
    vacation_hours = forms.IntegerField(required=False)
    overtime_hours = forms.IntegerField(required=False)
    date = forms.DateField(widget=forms.SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ),)

    class Meta:
        model = Month
        fields = ['date', 'work_hours', 'vacation_hours', 'overtime_hours']

payments/views.py
import os
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .models import Payment, Task, Month
from .forms import PaymentForm, TaskForm, MonthForm


def go_admin(request):
    return HttpResponseRedirect('/admin/')


def docs_view(request):
    return render(request, "payments/documents.html")


def hours_view(request):
    hours = Month.objects.all().order_by('-id')
    if request.method == 'POST':
        form = MonthForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = MonthForm()
    return render(request, "payments/hours.html", {'hours': hours,
                                                   'form': form})


def tasks_view(request):
    tasks = Task.objects.all().order_by('-id')
    if request.method == 'POST':
        done = request.POST.get('Done', False)
        reset = request.POST.get('Reset', False)
        update = request.POST.get('UpDate', False)
        if done:
            tasks.filter(pk=done).update(done=True)
        if reset:
            tasks.update(done=False)
        if update:
            dates = tasks.values_list('id', 'deadline')
            updated_dates = [(x[0], x[1] + relativedelta(months=1)) for x in dates]
            [tasks.filter(pk=x[0]).update(deadline=x[1]) for x in updated_dates]
        else:
            form = TaskForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user
                instance.save()
        form = TaskForm()
    else:
        form = TaskForm()
    warning_date = date.today() + timedelta(days=7)
    curr_date = date.today()
    return render(request, "payments/tasks.html", {'tasks': tasks,
                                                   'form': form,
                                                   'warning_date': warning_date,
                                                   'curr_date': curr_date})


def payments_view(request, curr_year=None, curr_month=None):
    if curr_month is None:
        curr_month = datetime.now().month
    if curr_year is None:
        curr_year = datetime.now().year
    payments = Payment.objects.all().order_by('-id').filter(date__month=curr_month, date__year=curr_year)
    if request.method == 'POST':
        edit_payments = Payment.objects.all().order_by('-id')
        paid = request.POST.get('Done', False)
        if paid:
            edit_payments.filter(pk=paid).update(paid=True)
            form = PaymentForm()
        else:
            form = PaymentForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user
                instance.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'), {'form': form,
                                                                            'payments': payments})
    else:
        form = PaymentForm()
    # distinct months for page filtering
    payments_dates = Payment.objects.values_list('date', flat=True)
    payments_months = list(set([x.month for x in payments_dates]))
    payments_months.sort(reverse=True)
    payments_years = list(set([x.year for x in payments_dates]))
    payments_years.sort(reverse=True)
    month_total = sum([payment.value * payment.category.percent/100 for payment in payments])
    month_saved = int(0.18 * float(month_total))
    data = {'payments': payments,
            'payments_months': payments_months,
            'payments_years': payments_years,
            'curr_month': curr_month,
            'curr_year': curr_year,
            'month_total': month_total,
            'month_saved': month_saved,
            'form': form}
    return render(request, "payments/payments.html", data)


def download(request):
    file_location = request.POST.get('FilePath', False)
    file_path = os.path.join(settings.MEDIA_ROOT, file_location)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

payments/templates/payments/documents.html
§{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <h3 class="panel-title">Payments</h3>
<!--            <p class="panel-subtitle">todo: payment form here</p>-->

            <form class="site-from" action=" {% url 'payments:payments' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="create">
            </form>
            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle">todo: date here</p>

            <table style="width:100%">
              <tr>
                <th>No.</th>
                <th>Paid</th>
                <th>Name</th>
                <th>Date</th>
                <th>Value [zł]</th>
                <th>Invoice</th>
                <th>Category</th>
                <th>Desc</th>
              </tr>

            <form class="site-form" action="{% url 'payments:download' %}" method="post" id="Download">

            {% for payment in payments %}
            {% csrf_token %}

              <tr>
                <td>{{ forloop.counter }}
                <td>
<!--                    {% if payment.paid %}-->
<!--                        <span class="lnr lnr-checkmark-circle" style="color:green"></span>-->
<!--                    {% else %}-->
<!--                        <button type="submit" form="GetDone" name="Done" value="{{ payment.id }}">-->
<!--                            <i class="lnr lnr-cross-circle" style="color:red"></i>-->
<!--                        </button>-->
<!--                    {% endif %}-->
                    {% if payment.paid %}
                        <i class="lnr lnr-checkmark-circle" style="color:green"></i>
                    {% else %}
                        <form class="site-form" action="{% url 'payments:payments' %}" method="post" id="GetDone">
                       {% csrf_token %}
                        <button type="submit" form="GetDone" name="Done" value="{{ payment.id }}">
                            <i class="lnr lnr-cross-circle" style="color:red"></i>
                        </button>
                        </form>
                    {% endif %}
                </td>
                <td>{{ payment.name }}</td>
                <td>{{ payment.date}}</td>
                <td>{{ payment.value }}</td>
                <td>{{ payment.invoice }}
                    {% if payment.invoice %}
                    <button type="submit" form="Download" name="FilePath" value="{{ payment.invoice }}">
                        <i class="lnr lnr-download" style="color:red"></i>
                    </button>
                    {% endif %}
                </td>
                <td>{{ payment.category }}</td>
                <td>{{ payment.description }}</td>
              </tr>

            {% endfor %}
            </form>
            </table>

            <!-- END MYBLOCK -->

        </div>
    </div>




{% endblock %}

payments/templates/payments/hours.html
§{% extends 'base.html' %}
{% load static from staticfiles %}

{% block headcontent %}

    <center>
        <h4>Hours</h4>
    </center>

{% endblock %}

{% block content %}

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->


            <p class="panel-subtitle"><u>Month hours table</u></p>

            <table style="width:100%">
              <tr>
                <th>No.</th>
                <th>Date</th>
                <th>Work hours</th>
                <th>Overtime hours</th>
                <th>Vacation hours</th>
              </tr>

            {% for month in hours %}
              <tr>
                <td>{{ forloop.revcounter }}</td>
                <td>{{ month.date }}</td>
                <td>{{ month.work_hours }}
                <td>{{ month.overtime_hours }}</td>
                <td>{{ month.vacation_hours }}</td>
              </tr>
            {% endfor %}
            </table>


            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle">Add hour report.</p>

            <form class="site-from" action=" {% url 'payments:hours' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="add">
            </form>

            <!-- END MYBLOCK -->

        </div>
    </div>

{% endblock %}

payments/templates/payments/payments.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block headcontent %}

    <center>
        <h4>Payments</h4>
    </center>

{% endblock %}

{% block content %}

   <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->
            <font class="panel-subtitle">Filter years: </font>
            {% for year in payments_years %}
                <a href="{% url 'payments:filter-payments' year curr_month %}" class="">
                    <span class="label label-default">[ {{ year }} ]</span>
                </a>
            {% endfor %}
            <br>
            <font class="panel-subtitle">Filter months: </font>
            {% for month in payments_months %}
                <a href="{% url 'payments:filter-payments' curr_year month %}" class="">
                    <span class="label label-default">[ {{ month }} ]</span>
                </a>
            {% endfor %}

            <!-- END MYBLOCK -->

        </div>
    </div>


    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle"><u>Actual payments for {% now "F Y" %}</u></p>


            <table style="width:100%">
              <tr>
                <th>No.</th>
                <th>Paid</th>
                <th>Name</th>
                <th>Date</th>
                <th>Value [zł]</th>
                <th>Invoice</th>
                <th>Category</th>
                <th>Desc</th>
              </tr>

            {% for payment in payments %}

              <tr>
                <td>{{ forloop.counter }}
                <td>
                    {% if payment.paid %}
                        <i class="lnr lnr-checkmark-circle" style="color:green"></i>
                    {% else %}
                        <form class="site-form" action="{% url 'payments:payments' %}" method="post" id="GetDone">
                            {% csrf_token %}
                            <button type="submit" form="GetDone" name="Done" value="{{ payment.id }}">
                                <i class="lnr lnr-cross-circle" style="color:red"></i>
                            </button>
                        </form>
                    {% endif %}
                </td>
                <td>{{ payment.name }}</td>
                <td>{{ payment.date}}</td>
                <td>{{ payment.value }}</td>
                <td>
                    {% if payment.invoice %}
                        <form class="site-form" action="{% url 'payments:download' %}" method="post" id="Download">
                        {% csrf_token %}
                            <button type="submit" form="Download" name="FilePath" value="{{ payment.invoice }}">
                                {{ payment.filename|truncatechars:30 }} <i class="lnr lnr-download" style="color:red"></i>
                            </button>
                        </form>
                    {% endif %}
                </td>
                <td>{{ payment.category }}</td>
                <td>{{ payment.description }}</td>
              </tr>

            {% endfor %}
            </table>

            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            Month total: {{ month_total }} [zł]
            Month saved: {{ month_saved }} [zł]


            <!-- END MYBLOCK -->

        </div>
    </div>


    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle">Add new payment.</p>

            <form class="site-from" action=" {% url 'payments:payments' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="create">
            </form>

            <!-- END MYBLOCK -->

        </div>
    </div>


{% endblock %}

payments/templates/payments/tasks.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block headcontent %}

    <center>
        <h4>Tasks</h4>
    </center>

{% endblock %}

{% block content %}

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <form class="site-form" action="{% url 'payments:tasks' %}" method="post" id="Reset">
           {% csrf_token %}
            <button type="submit" form="Reset" name="Reset" value="True">
                <i class="lnr lnr-trash" style="color:red">Reset tasks</i>
            </button>

            <button type="submit" form="Reset" name="UpDate" value="True">
                <i class="lnr lnr-magic-wand" style="color:blue">UpDate</i>
            </button>

            </form>

            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle"><u>Actual tasks table</u></p>

            <table style="width:100%">
              <tr>
                <th>No.</th>
                <th>Done</th>
                <th>Task</th>
                <th>Deadline</th>
              </tr>

            <form class="site-form" action="{% url 'payments:tasks' %}" method="post" id="GetDone">
            {% for task in tasks %}
            {% csrf_token   %}

              <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {% if task.done %}
                        <span class="lnr lnr-checkmark-circle" style="color:green"></span>
                    {% else %}
                        <button type="submit" form="GetDone" name="Done" value="{{ task.id }}">
                            <i class="lnr lnr-cross-circle" style="color:red"></i>
                        </button>
                    {% endif %}
                </td>
                <td>{{ task.name}}</td>
                <td>
                    {{ task.deadline }}
                        {% if task.deadline <= curr_date and task.done == False %}
                            <img src="{% static '/assets/img/skull-crossbones-solid.svg' %}" width="15x"/>
                            <img src="{% static '/assets/img/skull-crossbones-solid.svg' %}" width="15x"/>
                            <img src="{% static '/assets/img/skull-crossbones-solid.svg' %}" width="15x"/>
                        {% elif task.deadline < warning_date and task.done == False %}
                            <span class="label label-danger">deadline is coming</span>
                        {% else %}
                        {% endif %}
                </td>
              </tr>
            {% endfor %}
            </form>
            </table>

            <!-- END MYBLOCK -->

        </div>
    </div>

    <div class="panel panel-headline">
        <div class="panel-heading">

            <!-- MYBLOCK -->

            <p class="panel-subtitle">Add new task.</p>

            <form class="site-from" action=" {% url 'payments:tasks' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="create">
            </form>

            <!-- END MYBLOCK -->

        </div>
    </div>

{% endblock %}