Hepterakt/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from payments import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.payments_view),
    url(r'^payments/', include('payments.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^board/', include('board.urls')),
]

accounts/urls.py
from django.conf.urls import url

from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^login/", views.login_view, name="login"),
    url(r"^logout/", views.logout_view, name="logout"),
]

board/urls.py
from django.conf.urls import url

from . import views

app_name = "board"

urlpatterns = [
    url(r"^$", views.board, name="board"),
    url(r"^task/(?P<task_id>[-\w]+)/$", views.edit_task, name="edit-task"),
]

payments/urls.py
from django.conf.urls import url

from . import views

app_name = "payments"

urlpatterns = [
    url(r'^$', views.payments_view, name='payments'),
    url(r'^admin/', views.go_admin, name="go-admin"),
    url(r'^tasks/', views.tasks_view, name='tasks'),
    url(r'^download/', views.download, name='download'),
    url(r'^documents/', views.docs_view, name='documents'),
    url(r"^(?P<curr_year>[-\w]+)/(?P<curr_month>[-\w]+)/$", views.payments_view, name="filter-payments"),
    url(r'^hours/', views.hours_view, name='hours'),
]

templates/base.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">

<head>
	<title>Hepterakt</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static '/assets/vendor/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static '/assets/vendor/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static '/assets/vendor/chartist/css/chartist-custom.css' %}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{% static '/assets/css/main.css' %}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="{% static '/assets/css/demo.css' %}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{% static '/assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static '/assets/img/favicon.png' %}">
</head>

<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="brand">
				<a href="index.html">
					<img src="{% static 'assets/img/hepterakt-logo.png' %}" width="70px" alt="Klorofil Logo" class="img-responsive logo">
				</a>

			</div>
			<div class="brand">
				<h1>Hepterakt</h1>
			</div>

			<div class="container-fluid">
				<div class="navbar-btn">
					<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
				</div>

						<!-- MIDDLE NAVBAR -->

						<div class="navbar-btn">
						{% block headcontent %}
						{% endblock %}
						</div>

						<!-- END MIDDLE NAVBAR -->

				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<h4><b>{% now "jS F Y" %}</b></h4>
						</li>
						<li></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static '/assets/img/logo-ruch.jpeg' %}" class="img-circle" alt="Avatar">
								<span>{{ user.username }}</span>
								<i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'accounts:logout' %}"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- END NAVBAR -->
		<!-- LEFT SIDEBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<br>
						<li><a href="{% url 'payments:payments' %}" class="inactive"><i class="lnr lnr-cart"></i> <span>Payments</span></a></li>
						<li><a href="{% url 'payments:tasks' %}" class="inactive"><i class="lnr lnr-rocket"></i> <span>Tasks</span></a></li>
						<li><a href="{% url 'payments:hours' %}" class=""><i class="lnr lnr-clock"></i> <span>Hours</span></a></li>
						<li><a href="{% url 'payments:documents' %}" class=""><i class="lnr lnr-file-empty"></i> <span>Documents</span></a></li>
						<li><a href="{% url 'payments:go-admin' %}" class=""><i class="lnr lnr-cog"></i> <span>Admin</span></a></li>
						<li><a href="{% url 'board:board' %}" class=""><i class="lnr lnr-hourglass"></i> <span>Board</span></a></li>
					</ul>
				</nav>
			</div>
		</div>
		<!-- END LEFT SIDEBAR -->
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->

							{% block content %}
							{% endblock %}

					<!-- END OVERVIEW -->
					<div class="row">
						<div class="col-md-6">
						</div>
						<div class="col-md-6">
						</div>
					</div>
					<div class="row">
						<div class="col-md-7">
						</div>
						<div class="col-md-5">
						</div>
					</div>
					<div class="row">
						<div class="col-md-4">
						</div>
						<div class="col-md-4">
						</div>
						<div class="col-md-4">
						</div>
					</div>
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<p class="copyright">&copy; 2019 <a href="https://msobiczewski.pythonanywhere.com" target="_blank">Miłosz Sobiczewski</a>. All Rights Reserved.</p>
			</div>
		</footer>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="{% static '/assets/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static '/assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static '/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static '/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static '/assets/vendor/chartist/js/chartist.min.js' %}"></script>
	<script src="{% static '/assets/scripts/klorofil-common.js' %}"></script>
	<script>
	$(function() {
		var data, options;

		// headline charts
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[23, 29, 24, 40, 25, 24, 35],
				[14, 25, 18, 34, 29, 38, 44],
			]
		};

		options = {
			height: 300,
			showArea: true,
			showLine: false,
			showPoint: false,
			fullWidth: true,
			axisX: {
				showGrid: false
			},
			lineSmooth: false,
		};

		new Chartist.Line('#headline-chart', data, options);


		// visits trend charts
		data = {
			labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			series: [{
				name: 'series-real',
				data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
			}, {
				name: 'series-projection',
				data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
			}]
		};

		options = {
			fullWidth: true,
			lineSmooth: false,
			height: "270px",
			low: 0,
			high: 'auto',
			series: {
				'series-projection': {
					showArea: true,
					showPoint: false,
					showLine: false
				},
			},
			axisX: {
				showGrid: false,

			},
			axisY: {
				showGrid: false,
				onlyInteger: true,
				offset: 0,
			},
			chartPadding: {
				left: 20,
				right: 20
			}
		};

		new Chartist.Line('#visits-trends-chart', data, options);


		// visits chart
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[6384, 6342, 5437, 2764, 3958, 5068, 7654]
			]
		};

		options = {
			height: 300,
			axisX: {
				showGrid: false
			},
		};

		new Chartist.Bar('#visits-chart', data, options);


		// real-time pie chart
		var sysLoad = $('#system-load').easyPieChart({
			size: 130,
			barColor: function(percent) {
				return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
			},
			trackColor: 'rgba(245, 245, 245, 0.8)',
			scaleColor: false,
			lineWidth: 5,
			lineCap: "square",
			animate: 800
		});

		var updateInterval = 3000; // in milliseconds

		setInterval(function() {
			var randomVal;
			randomVal = getRandomInt(0, 100);

			sysLoad.data('easyPieChart').update(randomVal);
			sysLoad.find('.percent').text(randomVal);
		}, updateInterval);

		function getRandomInt(min, max) {
			return Math.floor(Math.random() * (max - min + 1)) + min;
		}

	});
	</script>
</body>

</html>